### get method
GET http://localhost:8000/

### POST 
POST http://localhost:8000/api/v1/user
Content-Type:application/json

{
    "name": "Prem Acharay",
    "email": "a@aq11.com",
    "pin": 1234
}



//===============Trans API
### get
GET http://localhost:8000/api/v1/transaction
Authorization: 63b8a53b81cdffb21c42f6e5


### add users transaction

### add users transactions
POST   http://localhost:8000/api/v1/transaction
Content-Type: application/json
Authorization: 63b902de402e90ed36bc0852

{
    "type": "income",
    "name" : "shopping",
    "amount": 122
}